name: qem
channels: 
        - conda-forge
dependencies:
        - pip
        - python=3.10
        - pip:
          - jupyterlab
          - matplotlib
          - numpy<2
          - qiskit==1.2.0
          - pylatexenc
          - qiskit-aer
          - qiskit-aer-gpu
          - pandas
          - python-dotenv
          - qiskit-ibm-provider
          - qiskit-ibm-runtime
          - mthree
          - qiskit-addon-cutting
          - seaborn
